#!/usr/bin/env python3
"""
Demonstration and testing script for automatic face recognition and logging.
This shows how the AutoAttendanceEngine works.
"""

from auto_mode import AutoAttendanceEngine
from datetime import datetime

# Mock callback for testing
def test_callback(result: dict) -> None:
    """Test callback to display results."""
    status = result.get("status", "unknown")
    message = result.get("message", "")
    full_name = result.get("full_name", "")
    confidence = result.get("confidence", 0.0)
    event_time = result.get("event_time", "")
    
    timestamp = datetime.now().strftime("%H:%M:%S")
    print(f"[{timestamp}] [{status.upper():12}] {message:40} | {full_name} ({confidence:.0%})")


def main():
    """Test the AutoAttendanceEngine."""
    print("\n" + "="*80)
    print("AUTOMATIC FACE RECOGNITION & ATTENDANCE SYSTEM - TEST DEMO")
    print("="*80)
    print()
    print("This demonstration shows what happens when you enable AUTO MODE:")
    print()
    print("1. The system initializes the AutoAttendanceEngine")
    print("2. It loads known employee face encodings from the database")
    print("3. It opens the camera and starts continuous scanning")
    print("4. For each frame:")
    print("   - Detects faces in real-time")
    print("   - Compares them against registered employees")
    print("   - Automatically logs attendance when recognized")
    print("   - Saves a snapshot of each detection")
    print("5. Anti-duplicate protection prevents duplicate logging (30s default)")
    print()
    print("-"*80)
    print("Engine State Machine:")
    print("-"*80)
    print()
    print("  Status         | Meaning")
    print("  ===============================================================")
    print("  error          | Error starting or during processing")
    print("  started        | Auto mode successfully started")
    print("  stopped        | Auto mode stopped by user")
    print("  scanning       | Currently scanning, no faces or multiple faces")
    print("  recognized     | Face matched to registered employee - LOGGED")
    print("  unknown        | Face detected but not recognized - LOGGED")
    print()
    print("-"*80)
    print("Data Flow:")
    print("-"*80)
    print()
    print("  Camera Feed")
    print("      ↓")
    print("  [Face Detection] → Extract faces from video frames")
    print("      ↓")
    print("  [Face Recognition] → Compare with known employees")
    print("      ↓")
    print("  [Decision]")
    print("      ├─→ Recognized Employee?")
    print("      │    └─→ Check anti-duplicate timer (30s)")
    print("      │         ├─→ Within 30s: Skip (prevent duplicate)")
    print("      │         └─→ After 30s: Log attendance → Database + Photo")
    print("      │")
    print("      └─→ Unknown Person?")
    print("           └─→ Always log as 'Unknown' → Database + Photo")
    print()
    print("-"*80)
    print("Database Logging:")
    print("-"*80)
    print()
    print("Each attendance is saved with:")
    print("  • Employee ID (if recognized)")
    print("  • Full Name")
    print("  • Event Type (IN/OUT)")
    print("  • Event Time (timestamp)")
    print("  • Confidence Score (face match accuracy)")
    print("  • Image Path (snapshot of the frame)")
    print()
    print("-"*80)
    print("File Organization:")
    print("-"*80)
    print()
    print("  photos/              - Employee registration photos")
    print("  logs/                - Attendance snapshots for known employees")
    print("  logs/unknown/        - Snapshots of unrecognized faces")
    print("  attendance.db        - SQLite database with all logs and employees")
    print()
    print("-"*80)
    print("How to Use AUTO MODE in the GUI:")
    print("-"*80)
    print()
    print("  1. Register at least one employee using the REGISTER EMPLOYEE panel")
    print("  2. Click '🤖 AUTO MODE ON' button in TURNSTILE CONTROL panel")
    print("  3. System will start continuous face scanning")
    print("  4. Whenever a registered employee is detected:")
    print("     ✅ Access is granted and attendance is automatically logged")
    print("     🚫 Unknown persons are also logged for security audit")
    print("  5. Click '🤖 AUTO MODE ON' again to stop scanning")
    print()
    print("="*80)
    print()
    
    # Initialize engine
    engine = AutoAttendanceEngine(callback=test_callback)
    
    print("Creating AutoAttendanceEngine instance...")
    print(f"  • Anti-duplicate protection: {engine.anti_duplicate_seconds} seconds")
    print(f"  • Engine ready: {not engine.running}")
    print()
    print("To actually use AUTO MODE:")
    print("  • Run: python app.py")
    print("  • Click the '🤖 AUTO MODE ON' button in the GUI")
    print()
    print("="*80 + "\n")


if __name__ == "__main__":
    main()
